logging:
  level:
    root: info
    com.example: debug
spring:
  datasource:
    name: LWCGDB,BJDB,SGSDB,HZDB,WNDB,YADB,TCDB,YLDB,AKDB,SLDB,XYDB,XADB,ODBDB,XXDB
    LWCGDB:
      url: jdbc:mysql://localhost:3306/lwcg?useUnicode=true&allowMultiQueries=true&characterEncoding=utf8&useSSL=true&autoReconnect=true&failOverReadOnly=false
      username: root
      password: root
    BJDB:
      url: jdbc:mysql://172.26.225.93:3306/car?useUnicode=true&characterEncoding=UTF-8&useSSL=true&autoReconnect=true&failOverReadOnly=false
      username: tidyinfo
      password: tidyinfo
    SGSDB:
      url: jdbc:mysql://172.26.225.101:3306/car?useUnicode=true&characterEncoding=UTF-8&useSSL=true&autoReconnect=true&failOverReadOnly=false
      username: tidyinfo
      password: tidyinfo
    HZDB:
      url: jdbc:mysql://172.26.225.91:3306/car?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&useSSL=true&autoReconnect=true&failOverReadOnly=false
      username: tidyinfo
      password: tidyinfo
    WNDB:
      url: jdbc:mysql://172.26.225.100:3306/car?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&useSSL=true&autoReconnect=true&failOverReadOnly=false
      username: tidyinfo
      password: tidyinfo
    YADB:
      url: jdbc:mysql://172.26.225.92:3306/car?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&useSSL=true&autoReconnect=true&failOverReadOnly=false
      username: tidyinfo
      password: tidyinfo
    TCDB:
      url: jdbc:mysql://172.26.225.94:3306/car?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&useSSL=true&autoReconnect=true&failOverReadOnly=false
      username: tidyinfo
      password: tidyinfo
    YLDB:
      url: jdbc:mysql://172.26.225.96:3306/car?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&useSSL=true&autoReconnect=true&failOverReadOnly=false
      username: tidyinfo
      password: tidyinfo
    AKDB:
      url: jdbc:mysql://172.26.225.95:3306/car?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&useSSL=true&autoReconnect=true&failOverReadOnly=false
      username: tidyinfo
      password: tidyinfo
    SLDB:
      url: jdbc:mysql://172.26.225.97:3306/car?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&useSSL=true&autoReconnect=true&failOverReadOnly=false
      username: tidyinfo
      password: tidyinfo
    XYDB:
      url: jdbc:mysql://172.26.225.99:3306/car?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&useSSL=true&autoReconnect=true&failOverReadOnly=false
      username: tidyinfo
      password: tidyinfo
    XADB:
      url:  jdbc:mysql://172.26.225.98:3306/car?useUnicode=true&allowMultiQueries=true&characterEncoding=utf8&useSSL=true&autoReconnect=true&failOverReadOnly=false
      username: tidyinfo
      password: tidyinfo
    XXDB:
      url: jdbc:mysql://172.26.225.103:3306/car?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&useSSL=true&autoReconnect=true&failOverReadOnly=false
      username: tidyinfo
      password: tidyinfo
    ODBDB:
      url: jdbc:mysql://183.221.250.177:7777/obd?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&useSSL=true&autoReconnect=true&failOverReadOnly=false
      username: root
      password: tidyinfo
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled:  true
        #合并多个DruidDataSource的监控数据
        #useGlobalDataSourceStat: true
        url-pattern:  /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        session-stat-enable:  true
        profile-enable: true
      stat-view-servlet:
        enabled:  true
        url-pattern:  /druid/*
        login-username: admin
        login-password: admin
        reset-enable: false
        allow:  127.0.0.1
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
          db-type: mysql
        wall:
          enabled: true
          db-type: mysql
          log-violation: true
          throw-exception: true
          config:
            alter-table-allow: false
            truncate-allow: false
            drop-table-allow: false
            none-base-statement-allow: false
            update-where-none-check: true
            select-into-outfile-allow: false
            metadata-allow: true
        slf4j:
          enabled: true
          connection-log-enabled: true
          connection-close-after-log-enabled: true
          connection-commit-after-log-enabled: true
          connection-connect-after-log-enabled: true
          connection-connect-before-log-enabled: true
          connection-log-error-enabled: true
          data-source-log-enabled: true
          result-set-log-enabled: true
          statement-log-enabled: true
